// Code generated by MockGen. DO NOT EDIT.
// Source: ./client.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	v1 "kubevirt.io/client-go/api/v1"
	v1alpha1 "kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateVirtualMachine mocks base method
func (m *MockClient) CreateVirtualMachine(vm *v1.VirtualMachine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVirtualMachine", vm)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVirtualMachine indicates an expected call of CreateVirtualMachine
func (mr *MockClientMockRecorder) CreateVirtualMachine(vm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVirtualMachine", reflect.TypeOf((*MockClient)(nil).CreateVirtualMachine), vm)
}

// ReadVirtualMachine mocks base method
func (m *MockClient) ReadVirtualMachine(namespace, name string) (*v1.VirtualMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadVirtualMachine", namespace, name)
	ret0, _ := ret[0].(*v1.VirtualMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadVirtualMachine indicates an expected call of ReadVirtualMachine
func (mr *MockClientMockRecorder) ReadVirtualMachine(namespace, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadVirtualMachine", reflect.TypeOf((*MockClient)(nil).ReadVirtualMachine), namespace, name)
}

// UpdateVirtualMachine mocks base method
func (m *MockClient) UpdateVirtualMachine(namespace, name string, vm *v1.VirtualMachine, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVirtualMachine", namespace, name, vm, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVirtualMachine indicates an expected call of UpdateVirtualMachine
func (mr *MockClientMockRecorder) UpdateVirtualMachine(namespace, name, vm, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVirtualMachine", reflect.TypeOf((*MockClient)(nil).UpdateVirtualMachine), namespace, name, vm, data)
}

// DeleteVirtualMachine mocks base method
func (m *MockClient) DeleteVirtualMachine(namespace, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVirtualMachine", namespace, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVirtualMachine indicates an expected call of DeleteVirtualMachine
func (mr *MockClientMockRecorder) DeleteVirtualMachine(namespace, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVirtualMachine", reflect.TypeOf((*MockClient)(nil).DeleteVirtualMachine), namespace, name)
}

// CreateDataVolume mocks base method
func (m *MockClient) CreateDataVolume(vm v1alpha1.DataVolume) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDataVolume", vm)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDataVolume indicates an expected call of CreateDataVolume
func (mr *MockClientMockRecorder) CreateDataVolume(vm interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDataVolume", reflect.TypeOf((*MockClient)(nil).CreateDataVolume), vm)
}

// ReadDataVolume mocks base method
func (m *MockClient) ReadDataVolume(namespace, name string) (*v1alpha1.DataVolume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDataVolume", namespace, name)
	ret0, _ := ret[0].(*v1alpha1.DataVolume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDataVolume indicates an expected call of ReadDataVolume
func (mr *MockClientMockRecorder) ReadDataVolume(namespace, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDataVolume", reflect.TypeOf((*MockClient)(nil).ReadDataVolume), namespace, name)
}

// UpdateDataVolume mocks base method
func (m *MockClient) UpdateDataVolume(namespace, name string, dv *v1alpha1.DataVolume, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDataVolume", namespace, name, dv, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDataVolume indicates an expected call of UpdateDataVolume
func (mr *MockClientMockRecorder) UpdateDataVolume(namespace, name, dv, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataVolume", reflect.TypeOf((*MockClient)(nil).UpdateDataVolume), namespace, name, dv, data)
}

// DeleteDataVolume mocks base method
func (m *MockClient) DeleteDataVolume(namespace, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDataVolume", namespace, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDataVolume indicates an expected call of DeleteDataVolume
func (mr *MockClientMockRecorder) DeleteDataVolume(namespace, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDataVolume", reflect.TypeOf((*MockClient)(nil).DeleteDataVolume), namespace, name)
}
